plugins {
    id 'fabric-loom' version '1.6-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release.set(17)
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

// Tích hợp ProGuard để obfuscate code chống dịch ngược
task obfuscateJar(type: proguard.gradle.ProGuardTask, dependsOn: remapJar) {
    injars remapJar.archiveFile
    outjars layout.buildDirectory.file("libs/${project.archivesBaseName}-${project.version}-obfuscated.jar")

    libraryjars "${System.getProperty('java.home')}/jmods"
    // Thêm các thư viện phụ thuộc của Minecraft/Fabric vào đây nếu cần thiết cho ProGuard
}
