#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, e.g.:
#           SHELL=/usr/bin/ksh ./gradlew
#
#       This script attempts to choose a POSIX-compliant shell automatically.
#
#   (2) This script uses the Gradle wrapper jar file at
#       `gradle/wrapper/gradle-wrapper.jar`. If you are missing that file, please
#       download it temporarily from:
#           https://raw.githubusercontent.com/gradle/gradle/v8.5.0/gradle/wrapper/gradle-wrapper.jar
#       and place it at `gradle/wrapper/gradle-wrapper.jar` in your project.
#
#       If you are using a Gradle version prior to 8.5, you may need to update
#       the wrapper jar file manually.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) : ;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # not a switch
              */*)  true ;;                             # contains a slash
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters below affects the iteration
        # in progress.  This is (currently) POSIX-compliant, which is a
        # feature, not a bug.
        set -- "$@" "$arg"
    done
fi

# Collect the arguments for the java command.
# * The default JVM options and the environment variables JAVA_OPTS and GRADLE_OPTS are added to the result.
# * The arguments after '--' are passed to the Java process as is, without the application's main class.
# * The main class name is the first argument to the Java command.
# * The '-D' and '-da' (among others) are Java system properties, and are passed as -Dappname=value (or similar).
# * The '-classpath' argument is also passed as-is.
# * The module path (if any) is passed as-is.

# JAVA_OPTS is a variable that users can pass extra JVM options to the Gradle command.
# GRADLE_OPTS is a variable that users can pass extra JVM options to the Gradle Wrapper.
# JAVA_TOOL_OPTIONS is an environment variable that can be used to set JVM options for
# any Java command (including this wrapper script) on some operating systems.

# The java command to run:
if [ -z "$JAVA_TOOL_OPTIONS" ]; then
    JAVA_CMD="exec \"$JAVACMD\""
else
    # JAVA_TOOL_OPTIONS is not a POSIX variable but a de-facto standard and is respected by all
    # Java commands we know of. However, we cannot use the standard 'exec' technique here because
    # that would discard the JAVA_TOOL_OPTIONS variable's values. In POSIX, we cannot pass
    # non-POSIX variables to a child process and have them be recognized. However, we can pass
    # the variable's values as part of the command line arguments.
    JAVA_CMD="exec \"$JAVACMD\" -Djava.awt.headless=true \"\$JAVA_TOOL_OPTIONS\""
fi

# The main class name is the first argument (without the '--' arguments).
MAIN_CLASS_NAME="org.gradle.wrapper.GradleWrapperMain"

# Collect the arguments, but then shift to remove the wrapper script's own arguments.
set -- \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    "$MAIN_CLASS_NAME" \
    "$@"

# Use "shift" to remove the wrapper script's arguments from the list of positional parameters.
shift

# Finally, execute the Java command with the list of arguments.
$JAVA_CMD "$@"
